[build]
    function = "netlify/functions"

[[redirects]] 
    from = "/.netlify/fucntions/*"
    to = "/.netlify/fucntions/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200